services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: storage_db
    environment:
      POSTGRES_DB: storage_db
      POSTGRES_USER: yourusername
      POSTGRES_PASSWORD: yourpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
